name: Continuous Delivery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cicd:
    uses: trialstudio/reusable_github_workflows/.github/workflows/maven_continuous_delivery.yml@main
    with:
      java_version: 11
      project_name: demo_java
    secrets:
      github_repo_token: ${{ secrets.GITHUB_TOKEN }}
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
  deploy:
    uses: trialstudio/reusable_github_workflows/.github/workflows/deploy_lambda_with_image.yml@main
    needs: cicd
    with:
      image: ${{ secrets.IMAGE_REPOSITORY }}:${{ needs.cicd.outputs.release_tag }}
      aws_region: ${{ inputs.aws_region }}
      function_name: ${{ secrets.FUNCTION_NAME }}
    secrets:
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}