name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: image version (same as tag) to deploy
      awsregion:
        type: string
        required: true
        description: aws region to deploy function
        default: "us-east-2"

jobs:
  deploy_to_dev:
    uses: trialstudio/reusable_github_workflows/.github/workflows/deploy_lambda_with_image.yml@main
    with:
      aws_region: ${{ github.event.inputs.awsregion }}
    secrets:
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
      image: ${{ secrets.IMAGE_REPOSITORY }}:${{ inputs.version }}
      function_name: ${{ secrets.FUNCTION_NAME }}
