name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: image version (same as tag) to deploy
      aws_region:
        type: string
        required: true
        description: aws region to deploy function
        default: "us-east-2"

jobs:
  deploy_to_dev:
    uses: trialstudio/reusable_github_workflows/.github/workflows/deploy_lambda_with_image.yml@main
    with:
      image: ${{ secrets.IMAGE_REPOSITORY }}:${{ inputs.version }}
      aws_region: ${{ inputs.aws_region }}
      function_name: ${{ secrets.FUNCTION_NAME }}
    secrets:
      aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}